name: Build Image from Dockerfile 
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build_x86_64_wheels:
    name: Build image for x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: lowercase repo-owner
      run: |
        # use Bash to convert to lowercase
        echo "REPO_OWNER_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.REPO_OWNER_LOWER }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile_x86_64
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/manylinux2014_x86_64-hdf5

  build_aarch64_wheels:
    name: Build image for aarch64
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.REPO_OWNER_LOWER }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile_aarch64
        platforms: linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/manylinux2014_aarch64-hdf5
